version: "2"

linters:
  default: none
  enable:
    - gofmt
    - goimports
    - govet
    - revive
    - errcheck
    - staticcheck
    - ineffassign
  settings:
    gofmt:
      simplify: true

run:
  timeout: 5m
  # 可选：路径模式，推荐使用 cfg 保持一致性
  relative-path-mode: cfg

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

# 如需自定义输出格式或路径，可参考官方 changelog
