version: 2
env:
- GO111MODULE=on
- CGO_ENABLED=0

before:
  hooks:
  - go mod tidy

builds:

- id: go-translator
  binary: go-translator
  main: ./cmd/translator
  ldflags:
  - -s -w
  - -X main.Version={{ .Version }}
  - -X main.BuildDate={{ .Date }}
  - -X main.Commit={{ .ShortCommit }}
  goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - "386"
  - amd64
  - arm64
  overrides:
  - goos: darwin
    goarch: amd64
    ldflags:
    - -s -w
    env:
    - CGO_ENABLED=0
  - goos: darwin
    goarch: arm64
    ldflags:
    - -s -w
    env:
    - CGO_ENABLED=0
  - goos: linux
    goarch: amd64
    ldflags:
    - -s -w -extldflags "-static"
    - -X main.Version={{ .Version }}
    - -X main.BuildDate={{ .Date }}
    - -X main.Commit={{ .ShortCommit }}

archives:

- id: go-translator
  builds:
  - go-translator
  format_overrides:
  - goos: windows
    format: zip
  files:
  - configs/default.yaml
  - README.md
  - LICENSE

release:
  github:
    owner: nerdneilsfield
    name: go-translator-agent

# dockers:
# - image_templates:
#   - 'nerdneils/translator:{{ .Tag }}-amd64'
#   - 'ghcr.io/nerdneilsfield/translator:{{ .Tag }}-amd64'
#   dockerfile: Dockerfile
#   use: buildx
#   build_flag_templates:
#   - "--pull"
#   - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/nerdneilsfield/go-translator-agent/master/README.md"
#   - "--label=io.artifacthub.package.maintainers=[{\"name\":\"dengqqi\",\"email\":\"dengqqi935@gmail.com\"}]"
#   - "--label=io.artifacthub.package.license=MIT"
#   - "--label=org.opencontainers.image.description=翻译工具是一个高质量、灵活的多语言翻译系统，采用三步翻译流程来确保翻译质量。"
#   - "--label=org.opencontainers.image.created={{.Date}}"
#   - "--label=org.opencontainers.image.name={{.ProjectName}}"
#   - "--label=org.opencontainers.image.revision={{.ShortCommit}}"
#   - "--label=org.opencontainers.image.version={{.Version}}"
#   - "--label=org.opencontainers.image.source={{.GitURL}}"
#   - "--platform=linux/amd64"
#   goarch: amd64
#   extra_files:
#   - "configs/default.yaml"
#   - "README.md"
# - image_templates:
#   - 'nerdneils/translator:{{ .Tag }}-arm64'
#   - 'ghcr.io/nerdneilsfield/translator:{{ .Tag }}-arm64'
#   dockerfile: Dockerfile
#   use: buildx
#   build_flag_templates:
#   - "--pull"
#   - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/nerdneilsfield/go-translator-agent/master/README.md"
#   - "--label=io.artifacthub.package.maintainers=[{\"name\":\"dengqqi\",\"email\":\"dengqqi935@gmail.com\"}]"
#   - "--label=io.artifacthub.package.license=MIT"
#   - "--label=org.opencontainers.image.description=翻译工具是一个高质量、灵活的多语言翻译系统，采用三步翻译流程来确保翻译质量。"
#   - "--label=org.opencontainers.image.created={{.Date}}"
#   - "--label=org.opencontainers.image.name={{.ProjectName}}"
#   - "--label=org.opencontainers.image.revision={{.ShortCommit}}"
#   - "--label=org.opencontainers.image.version={{.Version}}"
#   - "--label=org.opencontainers.image.source={{.GitURL}}"
#   - "--platform=linux/arm64"
#   goarch: arm64
#   extra_files:
#   - "configs/default.yaml"
#   - "README.md"

# docker_manifests:
# - name_template: 'nerdneils/translator:{{ .Tag }}'
#   image_templates:
#   - 'nerdneils/translator:{{ .Tag }}-amd64'
#   - 'nerdneils/translator:{{ .Tag }}-arm64'
# - name_template: 'ghcr.io/nerdneilsfield/translator:{{ .Tag }}'
#   image_templates:
#   - 'ghcr.io/nerdneilsfield/translator:{{ .Tag }}-amd64'
#   - 'ghcr.io/nerdneilsfield/translator:{{ .Tag }}-arm64'
# - name_template: 'nerdneils/translator:latest'
#   image_templates:
#   - 'nerdneils/translator:{{ .Tag }}-amd64'
#   - 'nerdneils/translator:{{ .Tag }}-arm64'
# - name_template: 'ghcr.io/nerdneilsfield/translator:latest'
#   image_templates:
#   - 'ghcr.io/nerdneilsfield/translator:{{ .Tag }}-amd64'
#   - 'ghcr.io/nerdneilsfield/translator:{{ .Tag }}-arm64'

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
  - title: 依赖更新
    regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
    order: 300
  - title: '新功能'
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 100
  - title: '错误修复'
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 200
  - title: '文档更新'
    regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
    order: 400
  - title: 其他工作
    order: 9999
