# Minimal config for testing
source_lang: "English"
target_lang: "Chinese"
country: "China"
default_model_name: "gpt-3.5-turbo"
active_step_set: "basic"

# Simple settings
chunk_size: 1000
concurrency: 2
request_timeout: 300
retry_attempts: 3
use_cache: false
debug: true

# Minimal models
models:
  gpt-3.5-turbo:
    name: "gpt-3.5-turbo"
    model_id: "gpt-3.5-turbo"
    api_type: "openai"
    base_url: "https://api.openai.com/v1"
    key: "sk-test-dummy-key"
    max_output_tokens: 4096
    max_input_tokens: 4096
    temperature: 0.7

# Basic step sets
step_sets:
  basic:
    id: "basic"
    name: "Basic Translation"
    description: "Basic three-step translation"
    initial_translation:
      name: "initial"
      model_name: "gpt-3.5-turbo"
      temperature: 0.5
    reflection:
      name: "reflection"
      model_name: "gpt-3.5-turbo"
      temperature: 0.3
    improvement:
      name: "improvement"
      model_name: "gpt-3.5-turbo"
      temperature: 0.5

# V2 step sets
step_sets_v2:
  basic:
    id: "basic"
    name: "Basic Translation V2"
    description: "Basic three-step translation"
    steps:
      - name: "initial_translation"
        provider: "openai"
        model_name: "gpt-3.5-turbo"
        temperature: 0.5
        max_tokens: 4096
        prompt: "Translate from {{source_lang}} to {{target_lang}}: {{text}}"
      - name: "reflection"
        provider: "openai"
        model_name: "gpt-3.5-turbo"
        temperature: 0.3
        max_tokens: 4096
        prompt: "Review this translation and identify issues: {{initial_translation}}"
      - name: "improvement"
        provider: "openai"
        model_name: "gpt-3.5-turbo"
        temperature: 0.5
        max_tokens: 4096
        prompt: "Improve this translation based on feedback: {{initial_translation}}"