source_lang = "English"
target_lang = "Chinese"

[translations]
# 常见专有名词
"Go" = "Go"
"Python" = "Python"
"JavaScript" = "JavaScript"
"TypeScript" = "TypeScript"
"Rust" = "Rust"
"Docker" = "Docker"
"Kubernetes" = "Kubernetes"
"Linux" = "Linux"
"Windows" = "Windows"
"macOS" = "macOS"
"iOS" = "iOS"
"Android" = "安卓"
"Qi Deng" = "邓岂"

