# 格式化器配置示例
# 可以集成到主配置文件中

# 格式化选项
formatting:
  # 是否启用格式化
  enabled: true
  
  # 格式化时机
  timing:
    before_parse: true    # 解析前格式化（确保输入规范）
    after_process: false  # 处理后格式化（保持翻译原样）
    before_render: false  # 渲染前格式化
    after_render: true    # 渲染后格式化（美化输出）
  
  # 通用选项
  options:
    preserve_whitespace: false
    max_line_length: 80
    tab_size: 4
    line_ending: "\n"  # 或 "\r\n" for Windows
    
  # 保护块配置
  preserve_blocks:
    - type: code
      pattern: '```[\s\S]*?```'
    - type: latex
      pattern: '\$\$[\s\S]*?\$\$'
    - type: inline_latex
      pattern: '\$[^$]+\$'
    - type: url
      pattern: 'https?://[^\s]+'
    - type: citation
      pattern: '\[@[^\]]+\]'
  
  # 外部工具配置
  external_tools:
    # Prettier 配置
    prettier:
      enabled: true
      command: prettier
      args:
        - --write
        - --print-width=80
        - --tab-width=4
      formats:
        - markdown
        - html
        - css
        - javascript
    
    # LaTeX indent 配置
    latexindent:
      enabled: true
      command: latexindent
      args:
        - -w
      formats:
        - latex
    
    # Black (Python) 配置
    black:
      enabled: false
      command: black
      args:
        - --line-length=88
      formats:
        - python

# 格式特定配置
format_specific:
  markdown:
    # Markdown 特定选项
    formatter: prettier  # 或 "builtin"
    options:
      # 统一列表标记
      list_marker: "-"
      # 标题前后空行
      heading_spacing: true
      # 表格对齐
      table_alignment: true
  
  text:
    # 文本特定选项
    formatter: builtin
    options:
      # 自动检测编码
      auto_detect_encoding: true
      # 中英文分别处理
      smart_wrap: true
  
  html:
    # HTML 特定选项
    formatter: prettier
    options:
      # 保留属性顺序
      preserve_attribute_order: true
      # 格式化内联样式
      format_inline_styles: false

# 格式化管道（高级功能）
formatting_pipelines:
  # 翻译前管道
  pre_translation:
    - format: markdown
      formatter: prettier
      options:
        print_width: 120
    - format: text
      formatter: builtin
      options:
        max_line_length: 0  # 不限制行长
  
  # 翻译后管道
  post_translation:
    - format: markdown
      formatter: builtin
      options:
        preserve_blocks:
          - type: translated_marker
            pattern: '<!-- translated:.*?-->'
    - format: markdown
      formatter: prettier
      continue_on_error: true