# 格式修复配置示例

# 基本翻译配置
source_lang: "English"
target_lang: "Chinese"
country: "China"

# 格式修复配置
enable_format_fix: true              # 启用格式修复
format_fix_interactive: false        # 使用静默自动修复模式
pre_translation_fix: true            # 启用翻译前格式修复
post_translation_fix: true           # 启用翻译后格式修复
use_external_tools: true             # 优先使用外部工具（如markdownlint、prettier）

# 按格式启用/禁用修复
format_fix_markdown: true            # 启用Markdown格式修复
format_fix_text: true                # 启用Text格式修复
format_fix_html: false               # HTML修复暂未实现
format_fix_epub: false               # EPUB修复暂未实现

# 翻译相关配置
chunk_size: 2000
retry_attempts: 3
use_cache: true
debug: false

# 示例步骤集配置
active_step_set: "basic"

# 示例模型配置
models:
  gpt-3.5-turbo:
    name: "gpt-3.5-turbo"
    model_id: "gpt-3.5-turbo"
    api_type: "openai"
    base_url: "https://api.openai.com/v1"
    max_output_tokens: 4000
    max_input_tokens: 16000
    temperature: 0.3
    input_token_price: 0.0015
    output_token_price: 0.002
    price_unit: "1M tokens"

step_sets_v2:
  basic:
    id: "basic"
    name: "基础翻译"
    description: "简单的三步翻译流程"
    initial_translation:
      name: "初步翻译"
      model_name: "gpt-3.5-turbo"
      temperature: 0.3
    reflection:
      name: "反思"
      model_name: "gpt-3.5-turbo"
      temperature: 0.1
    improvement:
      name: "改进"
      model_name: "gpt-3.5-turbo"
      temperature: 0.2
    fast_mode_threshold: 100