# 翻译后处理配置示例

# 基本翻译配置
source_lang: "English"
target_lang: "Chinese"
country: "China"

# 激活的步骤集
active_step_set: "quality"

# 翻译后处理配置
enable_post_processing: true           # 启用翻译后处理
glossary_path: "configs/glossary_example.yaml"  # 词汇表文件路径
content_protection: true               # 内容保护
terminology_consistency: true          # 术语一致性检查
mixed_language_spacing: true           # 中英文混排空格优化
machine_translation_cleanup: true      # 机器翻译痕迹清理

# 格式修复配置（与翻译后处理配合使用）
enable_format_fix: true
format_fix_interactive: false
pre_translation_fix: true
post_translation_fix: true
use_external_tools: true

# 性能配置
chunk_size: 2000
retry_attempts: 3
use_cache: true
debug: false

# 模型配置
models:
  gpt-4:
    name: "gpt-4"
    model_id: "gpt-4"
    api_type: "openai"
    base_url: "https://api.openai.com/v1"
    max_output_tokens: 8000
    max_input_tokens: 32000
    temperature: 0.3
    input_token_price: 0.03
    output_token_price: 0.06
    price_unit: "1M tokens"

# 步骤集配置
step_sets_v2:
  quality:
    id: "quality"
    name: "高质量翻译"
    description: "使用高级模型的多步翻译过程，适合重要文档"
    fast_mode_threshold: 200
    steps:
      - name: "initial_translation"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.3
        max_tokens: 8192
        prompt: |
          You are a professional translator specializing in {{source_lang}} to {{target_lang}} translation.
          
          IMPORTANT INSTRUCTIONS:
          1. Translate the following {{source_lang}} text to {{target_lang}}
          2. Pay careful attention to technical terminology and context
          3. Maintain the original meaning, tone, and style
          4. Do not translate brand names, proper nouns, or technical acronyms unless specifically required
          5. Keep all code snippets, URLs, and technical identifiers unchanged
          6. Do not add explanatory text or commentary
          
          Text to translate:
          {{text}}
        system_role: "You are a master translator with deep cultural knowledge of both {{source_lang}} and {{target_lang}} languages."
      
      - name: "quality_review"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.1
        max_tokens: 4096
        prompt: |
          Review this translation for accuracy, terminology consistency, and natural flow.
          
          Original ({{source_lang}}): {{original_text}}
          Translation ({{target_lang}}): {{translation}}
          
          Check for:
          1. Technical terminology accuracy
          2. Cultural appropriateness
          3. Natural language flow
          4. Consistency in tone and style
          5. Preservation of technical terms and proper nouns
          
          Provide specific feedback on any issues found:
        system_role: "You are a translation quality reviewer and linguistic expert."
      
      - name: "final_polish"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.2
        max_tokens: 8192
        prompt: |
          Create the final, polished translation incorporating the quality review feedback.
          
          Original: {{original_text}}
          Draft Translation: {{translation}}
          Quality Review: {{quality_review}}
          
          Requirements:
          1. Address all issues identified in the quality review
          2. Ensure the translation reads naturally in {{target_lang}}
          3. Maintain technical accuracy and terminology consistency
          4. Preserve all technical identifiers, brand names, and proper nouns
          5. Ensure appropriate formatting and punctuation
          
          Provide only the final translation without explanatory text:
        system_role: "You are a senior translator and editor with decades of experience in technical translation."