source_lang = "English"
target_lang = "Chinese"

[translations]
"Qi Deng" = "邓岂"
"Hao Sun" = "孙豪"
"Yuhao Shu" = "束宇豪"
"Yajun Hao" = "哈亚军"
"Weixiong Jiang" = "姜伟雄"
"Hui Wang" = "汪辉"
"Jianzhong Xiao" = "肖建中"
