# StepSets 配置示例
# 展示如何配置不同的翻译步骤集

# 基本翻译配置
source_lang: "English"
target_lang: "Chinese"
country: "China"

# 当前激活的步骤集
active_step_set: "professional"

# 基本翻译配置
chunk_size: 2000
retry_attempts: 3
use_cache: true
debug: false

# 格式修复配置
enable_format_fix: true
format_fix_interactive: false
pre_translation_fix: true
post_translation_fix: true
use_external_tools: true

# 模型配置
models:
  gpt-3.5-turbo:
    name: "gpt-3.5-turbo"
    model_id: "gpt-3.5-turbo"
    api_type: "openai"
    base_url: "https://api.openai.com/v1"
    max_output_tokens: 4000
    max_input_tokens: 16000
    temperature: 0.3
    input_token_price: 0.0015
    output_token_price: 0.002
    price_unit: "1M tokens"
  
  gpt-4:
    name: "gpt-4"
    model_id: "gpt-4"
    api_type: "openai"
    base_url: "https://api.openai.com/v1"
    max_output_tokens: 8000
    max_input_tokens: 32000
    temperature: 0.3
    input_token_price: 0.03
    output_token_price: 0.06
    price_unit: "1M tokens"

  deepl:
    name: "deepl"
    model_id: "deepl"
    api_type: "deepl"
    base_url: "https://api.deepl.com/v2"
    input_token_price: 0.02
    output_token_price: 0.02
    price_unit: "1M tokens"

# 新格式步骤集配置（支持灵活的步骤数量和提供商）
step_sets_v2:
  basic:
    id: "basic"
    name: "基本翻译"
    description: "使用单一模型的三步翻译过程"
    fast_mode_threshold: 300
    steps:
      - name: "initial_translation"
        provider: "openai"
        model_name: "gpt-3.5-turbo"
        temperature: 0.5
        max_tokens: 4096
        prompt: "Translate the following {{source_lang}} text to {{target_lang}}. Maintain the original meaning, tone, and style:\n\n{{text}}"
        system_role: "You are a professional translator."
      
      - name: "reflection"
        provider: "openai"
        model_name: "gpt-3.5-turbo"
        temperature: 0.3
        max_tokens: 2048
        prompt: "Review this translation and identify any issues:\n\nOriginal: {{original_text}}\nTranslation: {{translation}}\n\nProvide specific feedback."
        system_role: "You are a translation quality reviewer."
      
      - name: "improvement"
        provider: "openai"
        model_name: "gpt-3.5-turbo"
        temperature: 0.5
        max_tokens: 4096
        prompt: "Improve this translation based on the feedback:\n\nOriginal: {{original_text}}\nTranslation: {{translation}}\nFeedback: {{feedback}}\n\nProvide an improved translation."
        system_role: "You are a professional translator focusing on quality improvement."

  professional:
    id: "professional"
    name: "专业翻译"
    description: "使用专业翻译服务 + AI 优化"
    fast_mode_threshold: 300
    steps:
      - name: "initial_translation"
        provider: "deepl"
        model_name: "deepl"
        temperature: 0
        prompt: "{{text}}"
      
      - name: "reflection"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.3
        max_tokens: 2048
        prompt: "Review this professional translation from {{source_lang}} to {{target_lang}}:\n\nOriginal: {{original_text}}\nTranslation: {{translation}}\n\nIdentify any cultural nuances, terminology issues, or areas for improvement."
        system_role: "You are an expert linguist specializing in {{source_lang}} to {{target_lang}} translation."
      
      - name: "improvement"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.3
        max_tokens: 4096
        prompt: "Refine this translation based on the feedback, ensuring it sounds natural in {{target_lang}}:\n\nOriginal: {{original_text}}\nTranslation: {{translation}}\nFeedback: {{feedback}}\n\nProvide a polished final translation."
        system_role: "You are a native {{target_lang}} speaker and professional editor."

  fast:
    id: "fast"
    name: "快速翻译"
    description: "使用单一专业服务快速翻译"
    fast_mode_threshold: 10000
    steps:
      - name: "translation"
        provider: "deepl"
        model_name: "deepl"
        temperature: 0
        prompt: "{{text}}"

  quality:
    id: "quality"
    name: "高质量翻译"
    description: "使用高级模型的多步翻译过程"
    fast_mode_threshold: 200
    steps:
      - name: "initial_translation"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.3
        max_tokens: 8192
        prompt: "Translate the following {{source_lang}} text to {{target_lang}}. Pay careful attention to nuance, cultural context, and maintain the author's voice:\n\n{{text}}"
        system_role: "You are a master translator with deep cultural knowledge of both {{source_lang}} and {{target_lang}} languages."
      
      - name: "reflection"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.1
        max_tokens: 4096
        prompt: "Critically analyze this translation for accuracy, cultural appropriateness, and stylistic fidelity:\n\nOriginal: {{original_text}}\nTranslation: {{translation}}\n\nProvide detailed feedback on any issues."
        system_role: "You are a translation critic and linguistic expert."
      
      - name: "improvement"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.3
        max_tokens: 8192
        prompt: "Create the final, polished translation incorporating all feedback:\n\nOriginal: {{original_text}}\nDraft: {{translation}}\nFeedback: {{feedback}}\n\nEnsure the final version is publication-ready."
        system_role: "You are a senior translator and editor with decades of experience."

  mixed:
    id: "mixed"
    name: "混合模式"
    description: "结合多个提供商的优势"
    fast_mode_threshold: 500
    steps:
      - name: "initial_translation_deepl"
        provider: "deepl"
        model_name: "deepl"
        temperature: 0
        prompt: "{{text}}"
      
      - name: "initial_translation_openai"
        provider: "openai"
        model_name: "gpt-3.5-turbo"
        temperature: 0.3
        max_tokens: 4096
        prompt: "Translate the following {{source_lang}} text to {{target_lang}}:\n\n{{text}}"
        system_role: "You are a professional translator."
      
      - name: "comparison"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.2
        max_tokens: 3000
        prompt: "Compare these two translations and create the best version:\n\nOriginal ({{source_lang}}): {{original_text}}\n\nTranslation 1 (DeepL): {{initial_translation_deepl}}\nTranslation 2 (OpenAI): {{initial_translation_openai}}\n\nCombine the strengths of both to create an optimal {{target_lang}} translation."
        system_role: "You are an expert translator and linguist."
      
      - name: "polish"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.3
        max_tokens: 4096
        prompt: "Polish this final translation to ensure it reads naturally in {{target_lang}}:\n\nTranslation: {{comparison}}\n\nMake any final adjustments for fluency and naturalness."
        system_role: "You are a native {{target_lang}} speaker and professional editor."

  custom_academic:
    id: "custom_academic"
    name: "学术文档翻译"
    description: "专门用于学术文档的翻译流程"
    fast_mode_threshold: 150
    steps:
      - name: "terminology_extraction"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.1
        max_tokens: 2048
        prompt: "Extract key academic terms and concepts from this {{source_lang}} text:\n\n{{text}}\n\nList important terms that require careful translation."
        system_role: "You are an academic specialist in {{source_lang}} literature."
      
      - name: "initial_translation"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.3
        max_tokens: 8192
        prompt: "Translate this academic text from {{source_lang}} to {{target_lang}}, considering these key terms: {{terminology_extraction}}\n\nOriginal text:\n{{text}}\n\nMaintain academic tone and precision."
        system_role: "You are an academic translator specializing in scholarly texts."
      
      - name: "academic_review"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.1
        max_tokens: 3000
        prompt: "Review this academic translation for terminology consistency, citation style, and scholarly appropriateness:\n\nOriginal: {{original_text}}\nTranslation: {{translation}}\nKey Terms: {{terminology_extraction}}\n\nProvide feedback on academic accuracy."
        system_role: "You are a peer reviewer and academic editor."
      
      - name: "final_polish"
        provider: "openai"
        model_name: "gpt-4"
        temperature: 0.2
        max_tokens: 8192
        prompt: "Finalize this academic translation incorporating review feedback:\n\nOriginal: {{original_text}}\nDraft: {{translation}}\nReview: {{academic_review}}\n\nEnsure publication-ready quality."
        system_role: "You are a senior academic editor with expertise in {{target_lang}} scholarly writing."

# 旧格式步骤集（向后兼容）
step_sets:
  legacy_basic:
    id: "legacy_basic"
    name: "传统基础翻译"
    description: "旧格式的三步翻译"
    initial_translation:
      name: "初步翻译"
      model_name: "gpt-3.5-turbo"
      temperature: 0.3
    reflection:
      name: "反思"
      model_name: "gpt-3.5-turbo"
      temperature: 0.1
    improvement:
      name: "改进"
      model_name: "gpt-3.5-turbo"
      temperature: 0.2
    fast_mode_threshold: 300