# Go Translator Agent 配置文件
# 完全基于 internal/config/config.go 中的 Config 结构体

# 基本语言设置
source_lang: "English"
target_lang: "Chinese"
country: "China"

# 默认模型设置
default_model_name: "gpt-3.5-turbo"

# 活跃步骤集
active_step_set: "basic"

# 性能和并发设置
max_tokens_per_chunk: 2000
concurrency: 4
html_concurrency: 2
epub_concurrency: 5

# 超时设置
request_timeout: 300
translation_timeout: 1800
auto_save_interval: 300

# 分块设置
min_split_size: 100
max_split_size: 1000
chunk_size: 1000

# 重试设置
retry_attempts: 3
max_retries: 3
retry_failed_parts: true

# 缓存设置
use_cache: true
cache_dir: ""

# 调试设置
debug: false
save_debug_info: false
keep_intermediate_files: false
filter_reasoning: true

# 内容处理设置
preserve_math: true
translate_figure_captions: true

# Markdown 后处理设置
post_process_markdown: true
fix_math_formulas: true
fix_table_format: true
fix_mixed_content: true
fix_picture: true

# 格式修复设置
enable_format_fix: true
format_fix_interactive: true
pre_translation_fix: false
post_translation_fix: false
use_external_tools: true
format_fix_markdown: true
format_fix_text: true
format_fix_html: true
format_fix_epub: true

# 翻译后处理设置
enable_post_processing: true
glossary_path: "configs/glossary_example.yaml"
content_protection: true
terminology_consistency: true
mixed_language_spacing: true
machine_translation_cleanup: true

# 货币设置
target_currency: "USD"
usd_rmb_rate: 7.4

# 元数据
metadata: {}

# 模型配置
models:
  gpt-3.5-turbo:
    name: "gpt-3.5-turbo"
    model_id: "gpt-3.5-turbo"
    api_type: "openai"
    base_url: ""
    key: ""
    max_output_tokens: 4096
    max_input_tokens: 4096
    temperature: 0.7
    input_token_price: 0.5
    output_token_price: 1.5
    price_unit: "USD"
    is_reasoning: false

  gpt-4o:
    name: "gpt-4"
    model_id: "gpt-4"
    api_type: "openai"
    base_url: ""
    key: ""
    max_output_tokens: 8192
    max_input_tokens: 8192
    temperature: 0.7
    input_token_price: 2.5
    output_token_price: 10
    price_unit: "USD"
    is_reasoning: false

  o1-preview:
    name: "o1-preview"
    model_id: "o1-preview"
    api_type: "openai"
    base_url: ""
    key: ""
    max_output_tokens: 32768
    max_input_tokens: 128000
    temperature: 1
    input_token_price: 15
    output_token_price: 60
    price_unit: "USD"
    is_reasoning: true

  o1-mini:
    name: "o1-mini"
    model_id: "o1-mini"
    api_type: "openai"
    base_url: ""
    key: ""
    max_output_tokens: 65536
    max_input_tokens: 128000
    temperature: 1
    input_token_price: 3
    output_token_price: 12
    price_unit: "USD"
    is_reasoning: true

  deepseek-r1:
    name: "deepseek-r1"
    model_id: "deepseek-r1"
    api_type: "openai"
    base_url: "https://api.deepseek.com/v1"
    key: ""
    max_output_tokens: 8192
    max_input_tokens: 32768
    temperature: 0.7
    input_token_price: 0.14
    output_token_price: 2.19
    price_unit: "USD"
    is_reasoning: true
    reasoning_tags: ["<think>", "</think>"]

  qwq-32b:
    name: "qwq-32b"
    model_id: "qwq-32b-preview"
    api_type: "openai"
    base_url: ""
    key: ""
    max_output_tokens: 32768
    max_input_tokens: 32768
    temperature: 0.7
    is_reasoning: true
    reasoning_tags: ["<think>", "</think>"]

  qwen-plus:
    name: "qwen-plus"
    model_id: "qwen-plus"
    api_type: "openai"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    key: ""
    max_output_tokens: 8192
    max_input_tokens: 8192
    temperature: 0.7
    is_reasoning: false

  claude-3-opus:
    name: "claude-3-opus"
    model_id: "claude-3-opus-20240229"
    api_type: "anthropic"
    base_url: ""
    key: ""
    max_output_tokens: 4096
    max_input_tokens: 4096
    temperature: 0.7
    is_reasoning: false

  claude-3-sonnet:
    name: "claude-3-sonnet"
    model_id: "claude-3-sonnet-20240229"
    api_type: "anthropic"
    base_url: ""
    key: ""
    max_output_tokens: 4096
    max_input_tokens: 4096
    temperature: 0.7
    is_reasoning: false

  mistral-large:
    name: "mistral-large"
    model_id: "mistral-large-latest"
    api_type: "mistral"
    base_url: ""
    key: ""
    max_output_tokens: 8192
    max_input_tokens: 8192
    temperature: 0.7
    is_reasoning: false

  # 专业翻译服务配置
  deepl:
    name: "deepl"
    model_id: "deepl"
    api_type: "deepl"
    base_url: "https://api.deepl.com/v2"
    key: ""
    max_output_tokens: 130000
    max_input_tokens: 130000
    temperature: 0
    input_token_price: 0
    output_token_price: 0
    price_unit: "USD"
    is_reasoning: false

  deeplx:
    name: "deeplx"
    model_id: "deeplx"
    api_type: "deeplx"
    base_url: "http://localhost:1188/translate"
    key: ""
    max_output_tokens: 5000
    max_input_tokens: 5000
    temperature: 0
    input_token_price: 0
    output_token_price: 0
    price_unit: "USD"
    is_reasoning: false

  google-translate:
    name: "google-translate"
    model_id: "google-translate"
    api_type: "google"
    base_url: "https://translation.googleapis.com/language/translate/v2"
    key: ""
    max_output_tokens: 5000
    max_input_tokens: 5000
    temperature: 0
    input_token_price: 0
    output_token_price: 0
    price_unit: "USD"
    is_reasoning: false

  libretranslate:
    name: "libretranslate"
    model_id: "libretranslate"
    api_type: "libretranslate"
    base_url: "https://libretranslate.com"
    key: ""
    max_output_tokens: 5000
    max_input_tokens: 5000
    temperature: 0
    input_token_price: 0
    output_token_price: 0
    price_unit: "USD"
    is_reasoning: false

# 步骤集配置
step_sets:
  basic:
    id: "basic"
    name: "基本翻译"
    description: "基本的三步翻译过程"
    initial_translation:
      name: "初始翻译"
      model_name: "gpt-3.5-turbo"
      temperature: 0.5
    reflection:
      name: "反思"
      model_name: "gpt-3.5-turbo"
      temperature: 0.3
    improvement:
      name: "改进"
      model_name: "gpt-3.5-turbo"
      temperature: 0.5
    fast_mode_threshold: 300

  quality:
    id: "quality"
    name: "高质量翻译"
    description: "使用高级模型的翻译过程"
    initial_translation:
      name: "初始翻译"
      model_name: "gpt-4o"
      temperature: 0.5
    reflection:
      name: "反思"
      model_name: "claude-3-opus"
      temperature: 0.3
    improvement:
      name: "改进"
      model_name: "gpt-4o"
      temperature: 0.5
    fast_mode_threshold: 300

  reasoning:
    id: "reasoning"
    name: "推理翻译"
    description: "使用推理模型的深度翻译"
    initial_translation:
      name: "推理翻译"
      model_name: "deepseek-r1"
      temperature: 0.3
    reflection:
      name: "质量评估"
      model_name: "gpt-4o"
      temperature: 0.2
    improvement:
      name: "最终优化"
      model_name: "o1-mini"
      temperature: 0.3
    fast_mode_threshold: 100

# Step Sets V2 配置（新格式）
step_sets_v2:
  professional:
    id: "professional"
    name: "专业翻译"
    description: "使用专业翻译服务加AI优化"
    steps:
      - name: "initial_translation"
        provider: "deepl"
        model_name: "deepl"
        temperature: 0
        max_tokens: 4096
        prompt: "{{text}}"
        system_role: ""
      - name: "ai_review"
        provider: "openai"
        model_name: "gpt-4o"
        temperature: 0.2
        max_tokens: 3000
        prompt: |
          You are reviewing a translation from {{source_lang}} to {{target_lang}}.

          Original text:
          {{original_text}}

          Initial translation:
          {{initial_translation}}

          Please analyze this translation and identify any issues. Consider:
          1. Accuracy: Does the translation convey the exact meaning of the original?
          2. Fluency: Does the translation read naturally in {{target_lang}}?
          3. Terminology: Are technical terms, proper nouns, and specialized vocabulary translated appropriately?
          4. Formatting: Is all original formatting preserved (Markdown, LaTeX, HTML tags, etc.)?
          5. Consistency: Is the translation consistent throughout?
          6. Regional appropriateness: Is the language appropriate for {{country}}?

          Provide a detailed analysis of any issues found. If the translation is perfect, simply state that no issues were found.
        system_role: "You are an expert translation reviewer specializing in {{source_lang}} to {{target_lang}} translation quality assessment."
      - name: "final_polish"
        provider: "openai"
        model_name: "gpt-4o"
        temperature: 0.3
        max_tokens: 4096
        prompt: |
          You are improving a translation from {{source_lang}} to {{target_lang}} based on the following reflection.

          Original text:
          {{original_text}}

          Initial translation:
          {{initial_translation}}

          Reflection/Issues identified:
          {{ai_review}}

          Please provide an improved translation that addresses all the issues mentioned in the reflection while:
          1. Maintaining the exact meaning of the original text
          2. Ensuring natural fluency in {{target_lang}}
          3. Preserving all original formatting (Markdown, LaTeX, HTML tags, etc.)
          4. Using appropriate terminology and expressions
          5. Using language appropriate for {{country}}

          Provide only the improved translation without any explanation or commentary.
        system_role: "You are a professional {{target_lang}} editor specializing in translation refinement and quality improvement."
    fast_mode_threshold: 500

  multi_engine:
    id: "multi_engine"
    name: "多引擎对比翻译"
    description: "使用多个翻译引擎进行对比"
    steps:
      - name: "deepl_translation"
        provider: "deepl"
        model_name: "deepl"
        temperature: 0
        prompt: "{{text}}"
      - name: "google_translation"
        provider: "google"
        model_name: "google-translate"
        temperature: 0
        prompt: "{{text}}"
      - name: "ai_synthesis"
        provider: "openai"
        model_name: "gpt-4o"
        temperature: 0.2
        max_tokens: 4096
        prompt: |
          You have multiple translation engine results. Please compare and synthesize the best translation from {{source_lang}} to {{target_lang}}.

          Original text:
          {{original_text}}

          Translation results:
          1. DeepL: {{deepl_translation}}
          2. Google: {{google_translation}}

          Please analyze each translation considering:
          1. Accuracy: Which translation better captures the original meaning?
          2. Fluency: Which reads more naturally in {{target_lang}}?
          3. Terminology: Which handles technical terms and proper nouns better?
          4. Formatting: Which preserves the original formatting better?

          Based on your analysis, provide a final synthesized translation that combines the best aspects of all translations while:
          - Maintaining perfect accuracy to the original meaning
          - Ensuring natural fluency in {{target_lang}}
          - Preserving all original formatting (Markdown, LaTeX, HTML tags, etc.)
          - Using appropriate language for {{country}}

          Provide only the final synthesized translation without any explanation or analysis.
        system_role: "You are a professional translation expert specializing in multi-engine translation comparison and synthesis."
    fast_mode_threshold: 1000

  # LLM-based translation with comprehensive prompts
  llm_translation:
    id: "llm_translation"
    name: "LLM Complete Translation"
    description: "Full three-step translation using LLM models with detailed prompts"
    steps:
      - name: "initial_translation"
        provider: "openai"
        model_name: "gpt-4o"
        temperature: 0.3
        max_tokens: 4096
        prompt: |
          This is a translation task from {{source_lang}} to {{target_lang}}.

          Formatting Rules:
          1. Preserve all original formatting exactly:
             - Do not modify any Markdown syntax (**, *, #, etc.).
             - Do not translate any content within LaTeX formulas ($...$, $$...$$, \( ... \), \[ ... \]) or any LaTeX commands.
             - For LaTeX files, preserve all commands, environments (such as \begin{...} and \end{...}), and macros exactly as they are.
             - Keep all HTML tags intact.
          2. Do not alter abbreviations, technical terms, or code identifiers.
          3. Preserve document structure, including line breaks, paragraph spacing, lists, and tables.
          4. Use terminology and expressions appropriate for {{country}}.

          Please translate the following text:

          {{text}}
        system_role: "You are a professional translator specializing in {{source_lang}} to {{target_lang}} translation with expertise in preserving formatting and technical accuracy."
      - name: "reflection"
        provider: "openai"
        model_name: "gpt-4o"
        temperature: 0.2
        max_tokens: 3000
        prompt: |
          You are reviewing a translation from {{source_lang}} to {{target_lang}}.

          Original text:
          {{original_text}}

          Initial translation:
          {{initial_translation}}

          Please analyze this translation and identify any issues. Consider:
          1. Accuracy: Does the translation convey the exact meaning of the original?
          2. Fluency: Does the translation read naturally in {{target_lang}}?
          3. Terminology: Are technical terms, proper nouns, and specialized vocabulary translated appropriately?
          4. Formatting: Is all original formatting preserved (Markdown, LaTeX, HTML tags, etc.)?
          5. Consistency: Is the translation consistent throughout?
          6. Regional appropriateness: Is the language appropriate for {{country}}?

          Provide a detailed analysis of any issues found. If the translation is perfect, simply state that no issues were found.
        system_role: "You are an expert translation reviewer specializing in {{source_lang}} to {{target_lang}} translation quality assessment."
      - name: "improvement"
        provider: "openai"
        model_name: "gpt-4o"
        temperature: 0.3
        max_tokens: 4096
        prompt: |
          You are improving a translation from {{source_lang}} to {{target_lang}} based on the following reflection.

          Original text:
          {{original_text}}

          Initial translation:
          {{initial_translation}}

          Reflection/Issues identified:
          {{reflection}}

          Please provide an improved translation that addresses all the issues mentioned in the reflection while:
          1. Maintaining the exact meaning of the original text
          2. Ensuring natural fluency in {{target_lang}}
          3. Preserving all original formatting (Markdown, LaTeX, HTML tags, etc.)
          4. Using appropriate terminology and expressions
          5. Using language appropriate for {{country}}

          Provide only the improved translation without any explanation or commentary.
        system_role: "You are a professional {{target_lang}} editor specializing in translation refinement and quality improvement."
    fast_mode_threshold: 300