name: test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Setup go mod
        run: go mod tidy && go mod download
      -
        name: Run tests
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./tests/...
      -
        name: Check coverage
        run: go tool cover -func=coverage.out
      # -
      #   name: Upload coverage report
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.out
